# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ORRPS Limited
email: phil@orrps.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Business Analysis and Software Product Management services.
  Data Analysis services.
  IT-to-Business process transformation
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.orrps.co.uk" # the base hostname & protocol for your site
twitter_username: 
github_username:  f1wl

# Build settings
markdown: kramdown
